/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia.gui.config;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/**
 *
 * @author italo
 */
public class ConfigPNL extends javax.swing.JPanel {

    /**
     * Creates new form ConfigsPNL
     */
    public ConfigPNL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        margemPagTF = new javax.swing.JTextField();
        alterarMargemPagBT = new javax.swing.JButton();
        AutoCarregarModsCB = new javax.swing.JCheckBox();
        autoCarregarUsuariosCB = new javax.swing.JCheckBox();

        jLabel1.setText("Tolerância de pagamento:");

        alterarMargemPagBT.setText("Alterar");

        AutoCarregarModsCB.setText("Carregar tabela de modalidades automaticamente");

        autoCarregarUsuariosCB.setText("Carregar tabela de usuários automaticamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AutoCarregarModsCB)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(margemPagTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarMargemPagBT))
                    .addComponent(autoCarregarUsuariosCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(margemPagTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterarMargemPagBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoCarregarUsuariosCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AutoCarregarModsCB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAlterarToleranciaPagBT() {
        return alterarMargemPagBT;
    }

    public JTextField getToleranciaPagTF() {
        return margemPagTF;
    }

    public JCheckBox getAutoCarregarModsCB() {
        return AutoCarregarModsCB;
    }

    public JCheckBox getAutoCarregarUsuariosCB() {
        return autoCarregarUsuariosCB;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AutoCarregarModsCB;
    private javax.swing.JButton alterarMargemPagBT;
    private javax.swing.JCheckBox autoCarregarUsuariosCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField margemPagTF;
    // End of variables declaration//GEN-END:variables
}
